### PR TITLE
Add back a missing function that is used when computing power derivative

### PR DESCRIPTION
**Pull request by james34602**
Tested on power function

### CODE REVIEW

**Comment by martinResearch** [comment]
thank you for the contribution. I would like this code to be covered by new tests in https://github.com/martinResearch/MatlabAutoDiff/blob/master/src/AutoDiff_tests.m
with different input sizes to test all code paths in valXder if possible before merging.
at which revision did you find the code of the valXder function ?

**Comment by james34602** [comment]
I find a valXder function from [https://github.com/sehyoun/MATLABAutoDiff](https://github.com/sehyoun/MATLABAutoDiff).

The story is pretty simple, I try to optimize my z-plane model that uses a bunch of nonlinear function, pow() is needed, however, I get error for a missing function, this lead me search the internet for valXder function.

A little moment later, I finally found it, which file appear in sehyoun's repo, I immediately get his valXder into your library, bingo, it works, at least it work for my z-plane model that have multiple matrices and nonlinear function

**Comment by martinResearch** [comment]
good to hear it works. :) I'll try to find a solution with less additional code and add tests for it in the next few weeks

**Comment by martinResearch** [comment]
@james34602 I commited changes directly in master to solve your problem , could you confirm that solves your problem ?

**Comment by james34602** [comment]
> @james34602 I commited changes directly in master to solve your problem , could you confirm that solves your problem ?

Yes, it does, thanks.

**Comment by martinResearch** [comment]
closing the PR as it has been solved in the main branch

**Pull request closed without merging**
